### ISSUE TITLE
Higgs simplified analysis 

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#9]
(edited)
add the per-event bin number for Simplified Templated Cross sections

**Comment by gpetruc** [comment]
I think @dsperka had the code for computing that, maybe he can help?

**Comment by dsperka** [comment]
The instructions/code to do that is here:

https://twiki.cern.ch/twiki/bin/view/CMS/HiggsTemplateCrossSection

It is not completely inside standard CMSSW, since it depends on Rivet. Is that a problem for the nanoAOD?

**Comment by arizzi** [comment]
@perrozzi
is this part

`git cms-merge-topic -u perrozzi:HTXS_clean`

of the recipe still needed or the needed stuff has been integrated already?

**Comment by perrozzi** [comment]
I would say this is all, should be in cmssw already and was used to produce a few results too so validated.
@dsperka can confirm

**Comment by arizzi** [comment]
@perrozzi I do not see it in recent IB ... when was it integrated?

**Comment by perrozzi** [comment]
you are right, maybe was never integrated... I will prepare the rebase to master

**Comment by perrozzi** [comment]
https://github.com/cms-sw/cmssw/pull/20683

**Comment by arizzi** [comment]
@dsperka @perrozzi now that the central PRs are merged can you prepare a PR to store this info in nanoaod?

**Comment by perrozzi** [comment]
I still didn't put my hands on nano, can you please provide an example to start from?

**Comment by arizzi** [comment]
docs here: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD

you can see here different ways of creating global event variables:
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/globals_cff.py

**Comment by perrozzi** [comment]
Ciao, I need some help for dummies.
so far I did this https://github.com/cms-sw/cmssw/compare/564c740f3b595d579a012659cba71b3bf706e9b9...perrozzi:nanoAOD_htxs?expand=1
i.e. added a few producer and a sequence (which was a path in the original cfg) in `globals_cff.py` and added the sequence to `nanoSequenceMC` in `nano_cff.py`
I get the error below when running the 94x example in `sh runtests.sh`, can you please help me?

```
NANO,ENDJOB
entry /store/relval/CMSSW_9_4_0_pre3/RelValTTbar_13/MINIAODSIM/PU25ns_94X_mc2017_realistic_v4-v1/10000/52B94CC0-6FBB-E711-B577-0CC47A7C35F8.root
Step: NANO Spec:
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/bin/slc6_amd64_gcc630/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/bin/slc6_amd64_gcc630/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/Configuration/Applications/ConfigBuilder.py", line 2099, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/Configuration/Applications/ConfigBuilder.py", line 753, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = getattr(self,stepName+"DefaultSeq"))
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/Configuration/Applications/ConfigBuilder.py", line 1713, in prepare_NANO
    self.loadDefaultOrSpecifiedCFF(sequence,self.NANODefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/Configuration/Applications/ConfigBuilder.py", line 1200, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(defaultCFF)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/Configuration/Applications/ConfigBuilder.py", line 321, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/Config.py", line 583, in load
    self.extend(sys.modules[moduleName])
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/Config.py", line 624, in extend
    self.__setattr__(name,seq)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/Config.py", line 408, in __setattr__
    newValue._place(name,self)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/SequenceTypes.py", line 226, in _place
    self._placeImpl(name,proc)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/SequenceTypes.py", line 515, in _placeImpl
    proc._placeSequence(name,self)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/Config.py", line 540, in _placeSequence
    self._validateSequence(mod, name)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-15-1100/python/FWCore/ParameterSet/Config.py", line 747, in _validateSequence
    raise RuntimeError("An entry in sequence "+label + ' has no label')
RuntimeError: An entry in sequence globalrivetProducerHTXS has no label
Failure using cmsdriver 94X: status 1

```

**Comment by arizzi** [comment]
did we converge here?

**Comment by perrozzi** [comment]
close to

**Comment by arizzi** [comment]
any closer?

**Comment by perrozzi** [comment]
one click away
https://github.com/cms-sw/cmssw/pull/22025#issuecomment-381727854

**Comment by lenzip** [comment]
Hello, what is the status of this issue? Are STXS categories available in nanoAOD?

**Comment by arizzi** [comment]
I did not see a nanoaod PR.. I may have missed @perrozzi  can you comment? I think the one-click was made in the central repo, how about nano?

**Comment by perrozzi** [comment]
it should solve the problems I was encountering back in December

**Comment by peruzzim** [comment]
cms-sw#24753 is included in CMSSW_9_4_11_cand1, that has now been merged in the master branch.

Can you please test?

**Comment by adewit** [comment]
Hi, I have a working implementation for some private studies, starting from the initial commit linked above. See https://github.com/cms-nanoAOD/cmssw/compare/master...adewit:add-stxs?expand=1 - this works in CMSSW_9_4_11_cand1. I haven't tried in CMSSW_10_2_6 yet , but can do that if it's useful and make a PR. I don't know if @perrozzi (or anyone else) has been working on a more complete/better documented implementation, if so then I'll hold off on further development and keep my solution just for my own studies :-)

**Comment by lenzip** [comment]
Hi, can this proposal be finally merged so that we have this feature in nanoAOD. Without it no Higgs analysis can be performed because ggH theory incertainty rely on STXS categorization

**Comment by peruzzim** [comment]
Done in #227
